apiVersion: batch/v1
kind: Job
metadata:
  name: ingest-job
spec:
  completions: 4
  parallelism: 4
  completionMode: Indexed
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: ingest-container
        image: python:3.10
        volumeMounts:
        - name: nfs-volume
          mountPath: /data
        command:
          - "bash"
          - "-c"
          - |
            cd /data/viral-texts/scripts
            source .venv/bin/activate
            source setenv.sh
            python -u ingest.py /data/viral-texts/worker_${JOB_COMPLETION_INDEX}

      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: viraltexts-stage
